name: Deploy

on:
  workflow_run:
    workflows: ['Test Infrastructure', 'Test Lambda']
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest