name: Frontend

on:
  push:
    paths-ignore:
      - 'infrastructure/**'
      - 'backend/**'
      - 'README.md'
      - '.gitignore'
      - '.github/workflows/test_infrastructure.yaml'
      - '.github/workflows/deploy_infrastructure.yaml'
      - '.github/workflows/test_lambda.yaml'
      - '.github/workflows/deploy_lambda.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4