name: Test Lambda

on:
  push:
    paths-ignore:
      - 'infrastructure/**'
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Test
        run: python -m unittest lambda_test.py